---
name: Seerr
version: dev
slug: seerr
description: Request management and media discovery tool for the Plex and Jellyfin ecosystems
url: https://github.com/trumpetrhapsody/addon-seerr/tree/main/README.md
webui: http://[HOST]:[PORT:5055]
init: false
startup: application
arch:
  - aarch64
  - amd64
map:
  - addon_config:rw
ports:
  5055/tcp: 5055
options:
  host: "0.0.0.0"
  prefer_ipv4: true
schema:
  host: str
  prefer_ipv4: bool
watchdog: tcp://[HOST]:[PORT:5055]
